  mag_mse: 1.0
  phase_dot: 1.0
  phase_if: 0.5
  phase_aw_abs: 0.0
  time_consistency: 0.5
  wave_l1: 2.0
  mag_curric_min: 0.3
  mag_curric_max: 1.5
  mask_px: 0.0
  dice_w: 0.0
  damage_initial: 2.0
  damage_final: 0.3
  focal_gamma_init: 1.0
  focal_gamma_late: 1.5