# configs/loss_weights/debug.yaml

mag_mse: 1.0
phase_dot: 0.0
phase_if: 0.0
phase_aw_abs: 0.0
time_consistency: 0.0
wave_l1: 0.0
mag_curric_min: 0.3
mag_curric_max: 1.5
mask_px: 0.1
dice_w: 0.3
damage_initial: 1.0
damage_final: 0.5
focal_gamma_init: 1.5
focal_gamma_late: 1.0
