# diffusion.yaml
defaults:
  - _self_
  - default
  - loss_weights@loss_weights: base     # Register main loss weights
  # - loss_weights@debug_loss_weights: debug   # Optional debug override

debug_mode: false

model_name: "MultiModalLatentDiffusion"

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}


diffusion:
  train_autoencoders: true
  recompute_data: true
  dm_mode: "scratch"
  ckpt_path: "${output_dir}/diffusion/final_diffusion_model.pt"
  ae_ckpt_dir: "${output_dir}/autoencoders"
  latent_dim: 256
  batch_size: 200
  ae_epochs: 200
  ae_patience: 50
  ae_learning_rate: 5e-4
  num_epochs: 500
  learning_rate: 5e-4
  beta_start: 0.0001
  beta_end: 0.02
  num_timesteps: 1000

ae:
  spec_channels: 24
  freq_bins: 129
  time_bins: 24
  mask_shape: [32, 96]


