
# Launch WandB sweep for the dual-path autoencoder (AE) model on Euler:
# # 1. Load modules
# module load stack/2024-06
# module load gcc/12.2.0
# module load python_cuda/3.11.6

# # 2. Change to project root (where configs/ lives)
# cd /cluster/scratch/scansimo/DataSynthSHM

# # 3. Create the sweep
# wandb sweep configs/sweep_ae.yaml


# sweep_ae.yaml  –  searches loss-weight space for the dual-path AE
program: python

command:
  - python
  - -m
  - src.diff_pt.run
  - diffusion.train_autoencoders=true
  - debug_mode=false
  - ${args}

method: bayes
metric:
  name: val/spec
  goal: minimize

parameters:
  loss_weights.mag_mse:      {values: [0.0, 1.0]}
  loss_weights.phase_dot:    {values: [0.0, 1.0]}
  loss_weights.phase_if:     {values: [0.0, 1.0]}
  loss_weights.phase_aw_abs: {values: [0.0, 1.0]}
  loss_weights.time_consistency: {values: [0.0, 1.0]}
  loss_weights.wave_l1:          {values: [0.0, 1.0]}
  loss_weights.mask_px:          {values: [0.0, 1.0]}
  loss_weights.dice_w:           {values: [0.0, 1.0]}
  loss_weights.damage_initial:   {values: [0.0, 1.0]}
  loss_weights.damage_final:     {values: [0.0, 1.0]}
  loss_weights.focal_gamma_init: {values: [0.0, 1.0]}
  loss_weights.focal_gamma_late: {values: [0.0, 1.0]}

early_terminate:
  type: hyperband
  min_iter: 3
  max_iter: 30
