program: src/diff_pt/run.py
method: bayes
metric:
  name: val/spec
  goal: minimize
parameters:
  loss_weights.mag_mse:
    min: 0.1
    max: 3.0
  loss_weights.phase_dot:
    min: 0.1
    max: 3.0
  loss_weights.phase_if:
    values:
    - 0.0
    - 0.25
    - 0.5
    - 1.0
  loss_weights.phase_aw_abs:
    min: 0.0
    max: 1.0
  loss_weights.time_consistency:
    values:
    - 0.0
    - 0.25
    - 0.5
    - 1.0
  loss_weights.wave_l1:
    values:
    - 0.5
    - 1.0
    - 2.0
  loss_weights.mask_px:
    values:
    - 0.0
    - 0.1
    - 0.3
  loss_weights.damage_initial:
    min: 0.1
    max: 3.0
  loss_weights.damage_final:
    min: 0.1
    max: 1.0
  loss_weights.focal_gamma_init:
    values:
    - 1.0
    - 1.5
    - 2.0
  loss_weights.focal_gamma_late:
    values:
    - 1.0
    - 1.5
    - 2.0
  loss_weights.dice_w:
    min: 0.1
    max: 1.0
